language: node_js
cache:
    directories:
        - ~/.npm
node_js:
    - "12"
git:
    depth: 3
script:
    - npm build
deploy:
    provider: pages
    edge: true,
    skip-cleanup: true
    keep-history: true
    local-dir: public/
    github-token: $GITHUB_TOKEN
    target-branch: gh-pages
    commit_messages: "Deploy Website"
    on:
        branch: master
